# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'figma.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_figma(object):
    def setupUi(self, figma):
        figma.setObjectName("figma")
        figma.resize(619, 1024)
        figma.setStyleSheet("background: qradialgradient(cx:1.0, cy:0.0, radius: 3.0,\n"
"              fx:0.0, fy:1.0, stop:0 rgba(2, 2, 2, 0.75), stop:1 rgba(143, 99, 41, 0.75));")
        self.centralwidget = QtWidgets.QWidget(figma)
        self.centralwidget.setObjectName("centralwidget")
        self.timelabel = QtWidgets.QLabel(self.centralwidget)
        self.timelabel.setGeometry(QtCore.QRect(36, 15, 50, 9))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.timelabel.setFont(font)
        self.timelabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.timelabel.setObjectName("timelabel")
        self.menubtn = QtWidgets.QPushButton(self.centralwidget)
        self.menubtn.setGeometry(QtCore.QRect(540, 10, 18, 18))
        self.menubtn.setAutoFillBackground(False)
        self.menubtn.setStyleSheet("background: qradialgradient(cx:1.0, cy:0.0, radius: 3.0,\n"
"              fx:1.0, fy:0.0, stop:0 rgba(2, 2, 2, 0.75), stop:1 rgba(143, 99, 41, 0.75));\n"
"border-radius: 5px;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"")
        self.menubtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pics/HMI/icon/menu icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.menubtn.setIcon(icon)
        self.menubtn.setIconSize(QtCore.QSize(18, 18))
        self.menubtn.setObjectName("menubtn")
        self.recordframe = QtWidgets.QFrame(self.centralwidget)
        self.recordframe.setGeometry(QtCore.QRect(36, 58, 250, 125))
        self.recordframe.setStyleSheet("background: qradialgradient(cx:1.0, cy:0.0, radius: 3.0,\n"
"              fx:1.0, fy:0.0, stop:0 rgba(2, 2, 2, 0.75), stop:1 rgba(143, 99, 41, 0.75));\n"
"border-radius: 5px;\n"
"")
        self.recordframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.recordframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.recordframe.setObjectName("recordframe")
        self.recordlabel = QtWidgets.QLabel(self.recordframe)
        self.recordlabel.setGeometry(QtCore.QRect(80, 10, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.recordlabel.setFont(font)
        self.recordlabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.recordlabel.setLineWidth(0)
        self.recordlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.recordlabel.setObjectName("recordlabel")
        self.timer = QtWidgets.QLabel(self.recordframe)
        self.timer.setGeometry(QtCore.QRect(158, 100, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.timer.setFont(font)
        self.timer.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.timer.setLineWidth(0)
        self.timer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timer.setObjectName("timer")
        self.playsymbolback = QtWidgets.QLabel(self.recordframe)
        self.playsymbolback.setGeometry(QtCore.QRect(95, 50, 40, 40))
        self.playsymbolback.setAutoFillBackground(False)
        self.playsymbolback.setStyleSheet("background: #241F19;\n"
"box-shadow: inset 3px 3px 3px rgba(7, 6, 5, 0.25), inset -2px -2px 2px rgba(143, 99, 41, 0.25);\n"
"border-radius: 5px;\n"
"border-radius: 5px;")
        self.playsymbolback.setFrameShape(QtWidgets.QFrame.Box)
        self.playsymbolback.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.playsymbolback.setLineWidth(33)
        self.playsymbolback.setText("")
        self.playsymbolback.setScaledContents(False)
        self.playsymbolback.setObjectName("playsymbolback")
        self.playsymbol = QtWidgets.QLabel(self.recordframe)
        self.playsymbol.setGeometry(QtCore.QRect(105, 55, 20, 20))
        self.playsymbol.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.playsymbol.setText("")
        self.playsymbol.setPixmap(QtGui.QPixmap("pics/HMI/icon/play video button.svg"))
        self.playsymbol.setObjectName("playsymbol")
        self.audiosymbol = QtWidgets.QLabel(self.recordframe)
        self.audiosymbol.setGeometry(QtCore.QRect(115, 65, 15, 20))
        self.audiosymbol.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.audiosymbol.setText("")
        self.audiosymbol.setPixmap(QtGui.QPixmap("pics/HMI/icon/Audio Icon.svg"))
        self.audiosymbol.setObjectName("audiosymbol")
        self.waveslabel = QtWidgets.QLabel(self.recordframe)
        self.waveslabel.setGeometry(QtCore.QRect(30, 95, 120, 30))
        self.waveslabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.waveslabel.setText("")
        self.waveslabel.setPixmap(QtGui.QPixmap("pics/HMI/icon/Waves.svg"))
        self.waveslabel.setScaledContents(True)
        self.waveslabel.setObjectName("waveslabel")
        self.recordbtn = QtWidgets.QPushButton(self.recordframe)
        self.recordbtn.setGeometry(QtCore.QRect(0, 0, 250, 125))
        self.recordbtn.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.recordbtn.setText("")
        self.recordbtn.setObjectName("recordbtn")
        self.storagspace = QtWidgets.QFrame(self.centralwidget)
        self.storagspace.setGeometry(QtCore.QRect(312, 58, 250, 125))
        self.storagspace.setStyleSheet("background: qradialgradient(cx:1.0, cy:0.0, radius: 3.0,\n"
"              fx:1.0, fy:0.0, stop:0 rgba(2, 2, 2, 0.75), stop:1 rgba(143, 99, 41, 0.75));\n"
"border-radius: 5px;\n"
"")
        self.storagspace.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.storagspace.setFrameShadow(QtWidgets.QFrame.Raised)
        self.storagspace.setObjectName("storagspace")
        self.storagelabel = QtWidgets.QLabel(self.storagspace)
        self.storagelabel.setGeometry(QtCore.QRect(40, 10, 160, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.storagelabel.setFont(font)
        self.storagelabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.storagelabel.setLineWidth(0)
        self.storagelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.storagelabel.setObjectName("storagelabel")
        self.roundbrown = QtWidgets.QLabel(self.storagspace)
        self.roundbrown.setGeometry(QtCore.QRect(95, 50, 60, 60))
        self.roundbrown.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.roundbrown.setText("")
        self.roundbrown.setPixmap(QtGui.QPixmap("pics/HMI/icon/Storage golden side.svg"))
        self.roundbrown.setScaledContents(True)
        self.roundbrown.setObjectName("roundbrown")
        self.roundblack = QtWidgets.QLabel(self.storagspace)
        self.roundblack.setGeometry(QtCore.QRect(95, 50, 60, 60))
        self.roundblack.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.roundblack.setText("")
        self.roundblack.setPixmap(QtGui.QPixmap("pics/HMI/icon/Storage brown side.svg"))
        self.roundblack.setScaledContents(True)
        self.roundblack.setObjectName("roundblack")
        self.remain = QtWidgets.QLabel(self.storagspace)
        self.remain.setGeometry(QtCore.QRect(102, 70, 50, 10))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(7)
        self.remain.setFont(font)
        self.remain.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: #B99560;\n"
"border: 0px;")
        self.remain.setObjectName("remain")
        self.storagedatalabel = QtWidgets.QLabel(self.storagspace)
        self.storagedatalabel.setGeometry(QtCore.QRect(100, 82, 50, 10))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.storagedatalabel.setFont(font)
        self.storagedatalabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(152, 124, 88);")
        self.storagedatalabel.setAlignment(QtCore.Qt.AlignCenter)
        self.storagedatalabel.setObjectName("storagedatalabel")
        self.storagelabel.raise_()
        self.roundblack.raise_()
        self.remain.raise_()
        self.storagedatalabel.raise_()
        self.roundbrown.raise_()
        self.sdrmodule = QtWidgets.QFrame(self.centralwidget)
        self.sdrmodule.setGeometry(QtCore.QRect(312, 201, 250, 125))
        self.sdrmodule.setStyleSheet("background: qradialgradient(cx:1.0, cy:0.0, radius: 3.0,\n"
"              fx:1.0, fy:0.0, stop:0 rgba(2, 2, 2, 0.75), stop:1 rgba(143, 99, 41, 0.75));\n"
"border-radius: 5px;\n"
"")
        self.sdrmodule.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sdrmodule.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sdrmodule.setObjectName("sdrmodule")
        self.locationlabel_2 = QtWidgets.QLabel(self.sdrmodule)
        self.locationlabel_2.setGeometry(QtCore.QRect(40, 10, 160, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.locationlabel_2.setFont(font)
        self.locationlabel_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.locationlabel_2.setLineWidth(0)
        self.locationlabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.locationlabel_2.setObjectName("locationlabel_2")
        self.adsstatus = QtWidgets.QLabel(self.sdrmodule)
        self.adsstatus.setGeometry(QtCore.QRect(90, 100, 120, 11))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.adsstatus.setFont(font)
        self.adsstatus.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(143, 99, 41);")
        self.adsstatus.setLineWidth(0)
        self.adsstatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.adsstatus.setObjectName("adsstatus")
        self.label_5 = QtWidgets.QLabel(self.sdrmodule)
        self.label_5.setGeometry(QtCore.QRect(95, 50, 50, 50))
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("background: #241F19;\n"
"box-shadow: inset 3px 3px 3px rgba(7, 6, 5, 0.25), inset -2px -2px 2px rgba(143, 99, 41, 0.25);\n"
"border-radius: 5px;\n"
"border-radius: 5px;")
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_5.setLineWidth(33)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("pics/HMI/icon/ADS-B SDR.svg"))
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_12 = QtWidgets.QLabel(self.sdrmodule)
        self.label_12.setGeometry(QtCore.QRect(70, 100, 13, 11))
        self.label_12.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("pics/HMI/icon/eye icon.svg"))
        self.label_12.setScaledContents(False)
        self.label_12.setObjectName("label_12")
        self.latlong = QtWidgets.QFrame(self.centralwidget)
        self.latlong.setGeometry(QtCore.QRect(36, 201, 250, 125))
        self.latlong.setStyleSheet("background: qradialgradient(cx:1.0, cy:0.0, radius: 3.0,\n"
"              fx:1.0, fy:0.0, stop:0 rgba(2, 2, 2, 0.75), stop:1 rgba(143, 99, 41, 0.75));\n"
"border-radius: 5px;\n"
"")
        self.latlong.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.latlong.setFrameShadow(QtWidgets.QFrame.Raised)
        self.latlong.setObjectName("latlong")
        self.locationlabel = QtWidgets.QLabel(self.latlong)
        self.locationlabel.setGeometry(QtCore.QRect(40, 10, 160, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.locationlabel.setFont(font)
        self.locationlabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.locationlabel.setLineWidth(0)
        self.locationlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.locationlabel.setObjectName("locationlabel")
        self.latfix = QtWidgets.QLabel(self.latlong)
        self.latfix.setGeometry(QtCore.QRect(10, 50, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.latfix.setFont(font)
        self.latfix.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.latfix.setLineWidth(0)
        self.latfix.setAlignment(QtCore.Qt.AlignCenter)
        self.latfix.setObjectName("latfix")
        self.distancelabel = QtWidgets.QLabel(self.latlong)
        self.distancelabel.setGeometry(QtCore.QRect(10, 80, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.distancelabel.setFont(font)
        self.distancelabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.distancelabel.setLineWidth(0)
        self.distancelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.distancelabel.setObjectName("distancelabel")
        self.timelabel_2 = QtWidgets.QLabel(self.latlong)
        self.timelabel_2.setGeometry(QtCore.QRect(160, 80, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.timelabel_2.setFont(font)
        self.timelabel_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.timelabel_2.setLineWidth(0)
        self.timelabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.timelabel_2.setObjectName("timelabel_2")
        self.longfix = QtWidgets.QLabel(self.latlong)
        self.longfix.setGeometry(QtCore.QRect(160, 50, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.longfix.setFont(font)
        self.longfix.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.longfix.setLineWidth(0)
        self.longfix.setAlignment(QtCore.Qt.AlignCenter)
        self.longfix.setObjectName("longfix")
        self.straightbar = QtWidgets.QLabel(self.latlong)
        self.straightbar.setGeometry(QtCore.QRect(123, 50, 4, 50))
        self.straightbar.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.straightbar.setText("")
        self.straightbar.setPixmap(QtGui.QPixmap("pics/HMI/icon/gps road line.svg"))
        self.straightbar.setScaledContents(True)
        self.straightbar.setAlignment(QtCore.Qt.AlignCenter)
        self.straightbar.setObjectName("straightbar")
        self.label_4 = QtWidgets.QLabel(self.latlong)
        self.label_4.setGeometry(QtCore.QRect(110, 65, 30, 30))
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("pics/HMI/icon/gps icongps.svg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.Interiorcamera = QtWidgets.QFrame(self.centralwidget)
        self.Interiorcamera.setGeometry(QtCore.QRect(36, 345, 250, 125))
        self.Interiorcamera.setStyleSheet("background: qradialgradient(cx:1.0, cy:0.0, radius: 3.0,\n"
"              fx:1.0, fy:0.0, stop:0 rgba(2, 2, 2, 0.75), stop:1 rgba(143, 99, 41, 0.75));\n"
"border-radius: 5px;\n"
"")
        self.Interiorcamera.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Interiorcamera.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Interiorcamera.setObjectName("Interiorcamera")
        self.interiorcma = QtWidgets.QLabel(self.Interiorcamera)
        self.interiorcma.setGeometry(QtCore.QRect(30, 10, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.interiorcma.setFont(font)
        self.interiorcma.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.interiorcma.setLineWidth(0)
        self.interiorcma.setAlignment(QtCore.Qt.AlignCenter)
        self.interiorcma.setObjectName("interiorcma")
        self.incamstatus = QtWidgets.QLabel(self.Interiorcamera)
        self.incamstatus.setGeometry(QtCore.QRect(120, 105, 23, 11))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.incamstatus.setFont(font)
        self.incamstatus.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.incamstatus.setLineWidth(0)
        self.incamstatus.setAlignment(QtCore.Qt.AlignCenter)
        self.incamstatus.setObjectName("incamstatus")
        self.label_6 = QtWidgets.QLabel(self.Interiorcamera)
        self.label_6.setGeometry(QtCore.QRect(95, 50, 50, 50))
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("background: #241F19;\n"
"box-shadow: inset 3px 3px 3px rgba(7, 6, 5, 0.25), inset -2px -2px 2px rgba(143, 99, 41, 0.25);\n"
"border-radius: 5px;\n"
"border-radius: 5px;")
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_6.setLineWidth(33)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("pics/HMI/icon/Interior Camera.svg"))
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_13 = QtWidgets.QLabel(self.Interiorcamera)
        self.label_13.setGeometry(QtCore.QRect(100, 105, 13, 11))
        self.label_13.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("pics/HMI/icon/eye icon.svg"))
        self.label_13.setScaledContents(False)
        self.label_13.setObjectName("label_13")
        self.exteriorcamera = QtWidgets.QFrame(self.centralwidget)
        self.exteriorcamera.setGeometry(QtCore.QRect(312, 345, 250, 125))
        self.exteriorcamera.setStyleSheet("background: qradialgradient(cx:1.0, cy:0.0, radius: 3.0,\n"
"              fx:1.0, fy:0.0, stop:0 rgba(2, 2, 2, 0.75), stop:1 rgba(143, 99, 41, 0.75));\n"
"border-radius: 5px;\n"
"")
        self.exteriorcamera.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.exteriorcamera.setFrameShadow(QtWidgets.QFrame.Raised)
        self.exteriorcamera.setObjectName("exteriorcamera")
        self.excamera = QtWidgets.QLabel(self.exteriorcamera)
        self.excamera.setGeometry(QtCore.QRect(30, 10, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.excamera.setFont(font)
        self.excamera.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.excamera.setLineWidth(0)
        self.excamera.setAlignment(QtCore.Qt.AlignCenter)
        self.excamera.setObjectName("excamera")
        self.incamstatus_3 = QtWidgets.QLabel(self.exteriorcamera)
        self.incamstatus_3.setGeometry(QtCore.QRect(70, 120, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.incamstatus_3.setFont(font)
        self.incamstatus_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.incamstatus_3.setLineWidth(0)
        self.incamstatus_3.setText("")
        self.incamstatus_3.setAlignment(QtCore.Qt.AlignCenter)
        self.incamstatus_3.setObjectName("incamstatus_3")
        self.label_11 = QtWidgets.QLabel(self.exteriorcamera)
        self.label_11.setGeometry(QtCore.QRect(95, 50, 50, 50))
        self.label_11.setAutoFillBackground(False)
        self.label_11.setStyleSheet("background: #241F19;\n"
"box-shadow: inset 3px 3px 3px rgba(7, 6, 5, 0.25), inset -2px -2px 2px rgba(143, 99, 41, 0.25);\n"
"border-radius: 5px;\n"
"border-radius: 5px;")
        self.label_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_11.setLineWidth(33)
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("pics/HMI/icon/Exteior Camera.svg"))
        self.label_11.setScaledContents(False)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_14 = QtWidgets.QLabel(self.exteriorcamera)
        self.label_14.setGeometry(QtCore.QRect(100, 105, 13, 11))
        self.label_14.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("pics/HMI/icon/eye icon.svg"))
        self.label_14.setScaledContents(False)
        self.label_14.setObjectName("label_14")
        self.incamstatus_4 = QtWidgets.QLabel(self.exteriorcamera)
        self.incamstatus_4.setGeometry(QtCore.QRect(120, 105, 23, 11))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.incamstatus_4.setFont(font)
        self.incamstatus_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.incamstatus_4.setLineWidth(0)
        self.incamstatus_4.setAlignment(QtCore.Qt.AlignCenter)
        self.incamstatus_4.setObjectName("incamstatus_4")
        self.radioinput = QtWidgets.QFrame(self.centralwidget)
        self.radioinput.setGeometry(QtCore.QRect(312, 492, 250, 125))
        self.radioinput.setStyleSheet("background: qradialgradient(cx:1.0, cy:0.0, radius: 3.0,\n"
"              fx:1.0, fy:0.0, stop:0 rgba(2, 2, 2, 0.75), stop:1 rgba(143, 99, 41, 0.75));\n"
"border-radius: 5px;\n"
"")
        self.radioinput.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.radioinput.setFrameShadow(QtWidgets.QFrame.Raised)
        self.radioinput.setObjectName("radioinput")
        self.radio = QtWidgets.QLabel(self.radioinput)
        self.radio.setGeometry(QtCore.QRect(60, 10, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.radio.setFont(font)
        self.radio.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.radio.setLineWidth(0)
        self.radio.setAlignment(QtCore.Qt.AlignCenter)
        self.radio.setObjectName("radio")
        self.med = QtWidgets.QLabel(self.radioinput)
        self.med.setGeometry(QtCore.QRect(65, 65, 35, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.med.setFont(font)
        self.med.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.med.setLineWidth(0)
        self.med.setAlignment(QtCore.Qt.AlignCenter)
        self.med.setObjectName("med")
        self.low = QtWidgets.QLabel(self.radioinput)
        self.low.setGeometry(QtCore.QRect(65, 85, 35, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.low.setFont(font)
        self.low.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.low.setLineWidth(0)
        self.low.setAlignment(QtCore.Qt.AlignCenter)
        self.low.setObjectName("low")
        self.high = QtWidgets.QLabel(self.radioinput)
        self.high.setGeometry(QtCore.QRect(65, 45, 35, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.high.setFont(font)
        self.high.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.high.setLineWidth(0)
        self.high.setAlignment(QtCore.Qt.AlignCenter)
        self.high.setObjectName("high")
        self.roundblack_3 = QtWidgets.QLabel(self.radioinput)
        self.roundblack_3.setGeometry(QtCore.QRect(110, 50, 55, 55))
        self.roundblack_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.roundblack_3.setText("")
        self.roundblack_3.setPixmap(QtGui.QPixmap("pics/HMI/icon/Radio Input.svg"))
        self.roundblack_3.setScaledContents(False)
        self.roundblack_3.setObjectName("roundblack_3")
        self.cabinmic = QtWidgets.QFrame(self.centralwidget)
        self.cabinmic.setGeometry(QtCore.QRect(36, 492, 250, 125))
        self.cabinmic.setStyleSheet("background: qradialgradient(cx:1.0, cy:0.0, radius: 3.0,\n"
"              fx:1.0, fy:0.0, stop:0 rgba(2, 2, 2, 0.75), stop:1 rgba(143, 99, 41, 0.75));\n"
"border-radius: 5px;\n"
"")
        self.cabinmic.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cabinmic.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cabinmic.setObjectName("cabinmic")
        self.cabinmic_2 = QtWidgets.QLabel(self.cabinmic)
        self.cabinmic_2.setGeometry(QtCore.QRect(60, 10, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.cabinmic_2.setFont(font)
        self.cabinmic_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.cabinmic_2.setLineWidth(0)
        self.cabinmic_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cabinmic_2.setObjectName("cabinmic_2")
        self.micstatus = QtWidgets.QLabel(self.cabinmic)
        self.micstatus.setGeometry(QtCore.QRect(90, 100, 110, 11))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.micstatus.setFont(font)
        self.micstatus.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(143, 99, 41);")
        self.micstatus.setLineWidth(0)
        self.micstatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.micstatus.setObjectName("micstatus")
        self.roundblack_2 = QtWidgets.QLabel(self.cabinmic)
        self.roundblack_2.setGeometry(QtCore.QRect(95, 50, 50, 50))
        self.roundblack_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.roundblack_2.setText("")
        self.roundblack_2.setPixmap(QtGui.QPixmap("pics/HMI/icon/Cabin mic icon.svg"))
        self.roundblack_2.setScaledContents(True)
        self.roundblack_2.setObjectName("roundblack_2")
        self.label_15 = QtWidgets.QLabel(self.cabinmic)
        self.label_15.setGeometry(QtCore.QRect(70, 100, 13, 15))
        self.label_15.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("pics/HMI/icon/microphone icon.svg"))
        self.label_15.setScaledContents(False)
        self.label_15.setObjectName("label_15")
        self.wificard = QtWidgets.QFrame(self.centralwidget)
        self.wificard.setGeometry(QtCore.QRect(36, 638, 250, 125))
        self.wificard.setStyleSheet("background: qradialgradient(cx:1.0, cy:0.0, radius: 3.0,\n"
"              fx:1.0, fy:0.0, stop:0 rgba(2, 2, 2, 0.75), stop:1 rgba(143, 99, 41, 0.75));\n"
"border-radius: 5px;\n"
"")
        self.wificard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wificard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wificard.setObjectName("wificard")
        self.wificard_2 = QtWidgets.QLabel(self.wificard)
        self.wificard_2.setGeometry(QtCore.QRect(60, 10, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.wificard_2.setFont(font)
        self.wificard_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.wificard_2.setLineWidth(0)
        self.wificard_2.setAlignment(QtCore.Qt.AlignCenter)
        self.wificard_2.setObjectName("wificard_2")
        self.wificardstatus = QtWidgets.QLabel(self.wificard)
        self.wificardstatus.setGeometry(QtCore.QRect(90, 100, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.wificardstatus.setFont(font)
        self.wificardstatus.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.wificardstatus.setLineWidth(0)
        self.wificardstatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.wificardstatus.setObjectName("wificardstatus")
        self.roundblack_4 = QtWidgets.QLabel(self.wificard)
        self.roundblack_4.setGeometry(QtCore.QRect(90, 50, 50, 50))
        self.roundblack_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.roundblack_4.setText("")
        self.roundblack_4.setPixmap(QtGui.QPixmap("pics/HMI/icon/Wifi Card.svg"))
        self.roundblack_4.setScaledContents(True)
        self.roundblack_4.setObjectName("roundblack_4")
        self.label_16 = QtWidgets.QLabel(self.wificard)
        self.label_16.setGeometry(QtCore.QRect(70, 100, 20, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("pics/HMI/icon/wifi icon.svg"))
        self.label_16.setScaledContents(False)
        self.label_16.setObjectName("label_16")
        self.connecteddevice = QtWidgets.QFrame(self.centralwidget)
        self.connecteddevice.setGeometry(QtCore.QRect(320, 638, 250, 125))
        self.connecteddevice.setStyleSheet("background: qradialgradient(cx:1.0, cy:0.0, radius: 3.0,\n"
"              fx:1.0, fy:0.0, stop:0 rgba(2, 2, 2, 0.75), stop:1 rgba(143, 99, 41, 0.75));\n"
"border-radius: 5px;\n"
"")
        self.connecteddevice.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.connecteddevice.setFrameShadow(QtWidgets.QFrame.Raised)
        self.connecteddevice.setObjectName("connecteddevice")
        self.conecteddevice = QtWidgets.QLabel(self.connecteddevice)
        self.conecteddevice.setGeometry(QtCore.QRect(20, 10, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.conecteddevice.setFont(font)
        self.conecteddevice.setAutoFillBackground(False)
        self.conecteddevice.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.conecteddevice.setLineWidth(0)
        self.conecteddevice.setAlignment(QtCore.Qt.AlignCenter)
        self.conecteddevice.setObjectName("conecteddevice")
        self.high_2 = QtWidgets.QLabel(self.connecteddevice)
        self.high_2.setGeometry(QtCore.QRect(40, 50, 70, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.high_2.setFont(font)
        self.high_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.high_2.setLineWidth(0)
        self.high_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.high_2.setObjectName("high_2")
        self.high_3 = QtWidgets.QLabel(self.connecteddevice)
        self.high_3.setGeometry(QtCore.QRect(40, 75, 70, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.high_3.setFont(font)
        self.high_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.high_3.setLineWidth(0)
        self.high_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.high_3.setObjectName("high_3")
        self.high_4 = QtWidgets.QLabel(self.connecteddevice)
        self.high_4.setGeometry(QtCore.QRect(40, 100, 70, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.high_4.setFont(font)
        self.high_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.high_4.setLineWidth(0)
        self.high_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.high_4.setObjectName("high_4")
        self.high_5 = QtWidgets.QLabel(self.connecteddevice)
        self.high_5.setGeometry(QtCore.QRect(160, 50, 70, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.high_5.setFont(font)
        self.high_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.high_5.setLineWidth(0)
        self.high_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.high_5.setObjectName("high_5")
        self.devicelogo1 = QtWidgets.QLabel(self.connecteddevice)
        self.devicelogo1.setGeometry(QtCore.QRect(10, 50, 18, 18))
        self.devicelogo1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.devicelogo1.setText("")
        self.devicelogo1.setPixmap(QtGui.QPixmap("pics/HMI/icon/Phone icon.svg"))
        self.devicelogo1.setScaledContents(False)
        self.devicelogo1.setObjectName("devicelogo1")
        self.devicelogo3 = QtWidgets.QLabel(self.connecteddevice)
        self.devicelogo3.setGeometry(QtCore.QRect(10, 100, 18, 18))
        self.devicelogo3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.devicelogo3.setText("")
        self.devicelogo3.setPixmap(QtGui.QPixmap("pics/HMI/icon/Phone icon.svg"))
        self.devicelogo3.setScaledContents(False)
        self.devicelogo3.setObjectName("devicelogo3")
        self.devicelogo4 = QtWidgets.QLabel(self.connecteddevice)
        self.devicelogo4.setGeometry(QtCore.QRect(130, 50, 18, 18))
        self.devicelogo4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.devicelogo4.setText("")
        self.devicelogo4.setPixmap(QtGui.QPixmap("pics/HMI/icon/Phone icon.svg"))
        self.devicelogo4.setScaledContents(False)
        self.devicelogo4.setObjectName("devicelogo4")
        self.devicelogo2 = QtWidgets.QLabel(self.connecteddevice)
        self.devicelogo2.setGeometry(QtCore.QRect(10, 75, 18, 18))
        self.devicelogo2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.devicelogo2.setText("")
        self.devicelogo2.setPixmap(QtGui.QPixmap("pics/HMI/icon/Phone icon.svg"))
        self.devicelogo2.setScaledContents(False)
        self.devicelogo2.setObjectName("devicelogo2")
        self.devicelogo1_2 = QtWidgets.QLabel(self.connecteddevice)
        self.devicelogo1_2.setGeometry(QtCore.QRect(130, 100, 18, 18))
        self.devicelogo1_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.devicelogo1_2.setText("")
        self.devicelogo1_2.setPixmap(QtGui.QPixmap("pics/HMI/icon/Phone icon.svg"))
        self.devicelogo1_2.setScaledContents(False)
        self.devicelogo1_2.setObjectName("devicelogo1_2")
        self.devicelogo1_3 = QtWidgets.QLabel(self.connecteddevice)
        self.devicelogo1_3.setGeometry(QtCore.QRect(130, 75, 18, 18))
        self.devicelogo1_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.devicelogo1_3.setText("")
        self.devicelogo1_3.setPixmap(QtGui.QPixmap("pics/HMI/icon/Phone icon.svg"))
        self.devicelogo1_3.setScaledContents(False)
        self.devicelogo1_3.setObjectName("devicelogo1_3")
        self.high_6 = QtWidgets.QLabel(self.connecteddevice)
        self.high_6.setGeometry(QtCore.QRect(160, 75, 70, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.high_6.setFont(font)
        self.high_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.high_6.setLineWidth(0)
        self.high_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.high_6.setObjectName("high_6")
        self.high_7 = QtWidgets.QLabel(self.connecteddevice)
        self.high_7.setGeometry(QtCore.QRect(160, 100, 70, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.high_7.setFont(font)
        self.high_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.high_7.setLineWidth(0)
        self.high_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.high_7.setObjectName("high_7")
        self.ltemodule = QtWidgets.QFrame(self.centralwidget)
        self.ltemodule.setGeometry(QtCore.QRect(36, 788, 526, 125))
        self.ltemodule.setStyleSheet("background: qradialgradient(cx:1.0, cy:0.0, radius: 3.0,\n"
"              fx:1.0, fy:0.0, stop:0 rgba(2, 2, 2, 0.75), stop:1 rgba(143, 99, 41, 0.75));\n"
"border-radius: 5px;\n"
"")
        self.ltemodule.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ltemodule.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ltemodule.setLineWidth(0)
        self.ltemodule.setObjectName("ltemodule")
        self.locationlabel_10 = QtWidgets.QLabel(self.ltemodule)
        self.locationlabel_10.setGeometry(QtCore.QRect(190, 10, 140, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.locationlabel_10.setFont(font)
        self.locationlabel_10.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.locationlabel_10.setLineWidth(0)
        self.locationlabel_10.setAlignment(QtCore.Qt.AlignCenter)
        self.locationlabel_10.setObjectName("locationlabel_10")
        self.roundblack_5 = QtWidgets.QLabel(self.ltemodule)
        self.roundblack_5.setGeometry(QtCore.QRect(70, 50, 40, 40))
        self.roundblack_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.roundblack_5.setText("")
        self.roundblack_5.setPixmap(QtGui.QPixmap("pics/HMI/icon/Strength signal icon.svg"))
        self.roundblack_5.setScaledContents(True)
        self.roundblack_5.setObjectName("roundblack_5")
        self.storagedatalabel_2 = QtWidgets.QLabel(self.ltemodule)
        self.storagedatalabel_2.setGeometry(QtCore.QRect(70, 50, 50, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.storagedatalabel_2.setFont(font)
        self.storagedatalabel_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(152, 124, 88);")
        self.storagedatalabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.storagedatalabel_2.setObjectName("storagedatalabel_2")
        self.lteSignal = QtWidgets.QLabel(self.ltemodule)
        self.lteSignal.setGeometry(QtCore.QRect(40, 100, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lteSignal.setFont(font)
        self.lteSignal.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.lteSignal.setLineWidth(0)
        self.lteSignal.setAlignment(QtCore.Qt.AlignCenter)
        self.lteSignal.setObjectName("lteSignal")
        self.straightbar_2 = QtWidgets.QLabel(self.ltemodule)
        self.straightbar_2.setGeometry(QtCore.QRect(147, 40, 2, 50))
        self.straightbar_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.straightbar_2.setText("")
        self.straightbar_2.setPixmap(QtGui.QPixmap("pics/HMI/icon/gps road line.svg"))
        self.straightbar_2.setScaledContents(True)
        self.straightbar_2.setAlignment(QtCore.Qt.AlignCenter)
        self.straightbar_2.setObjectName("straightbar_2")
        self.roundblack_6 = QtWidgets.QLabel(self.ltemodule)
        self.roundblack_6.setGeometry(QtCore.QRect(182, 45, 45, 45))
        self.roundblack_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.roundblack_6.setText("")
        self.roundblack_6.setPixmap(QtGui.QPixmap("pics/HMI/icon/AWS Icon.svg"))
        self.roundblack_6.setScaledContents(True)
        self.roundblack_6.setObjectName("roundblack_6")
        self.awsConnectivity = QtWidgets.QLabel(self.ltemodule)
        self.awsConnectivity.setGeometry(QtCore.QRect(150, 100, 110, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.awsConnectivity.setFont(font)
        self.awsConnectivity.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.awsConnectivity.setLineWidth(0)
        self.awsConnectivity.setAlignment(QtCore.Qt.AlignCenter)
        self.awsConnectivity.setObjectName("awsConnectivity")
        self.straightbar_3 = QtWidgets.QLabel(self.ltemodule)
        self.straightbar_3.setGeometry(QtCore.QRect(259, 40, 2, 50))
        self.straightbar_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.straightbar_3.setText("")
        self.straightbar_3.setPixmap(QtGui.QPixmap("pics/HMI/icon/gps road line.svg"))
        self.straightbar_3.setScaledContents(True)
        self.straightbar_3.setAlignment(QtCore.Qt.AlignCenter)
        self.straightbar_3.setObjectName("straightbar_3")
        self.roundbrown_2 = QtWidgets.QLabel(self.ltemodule)
        self.roundbrown_2.setGeometry(QtCore.QRect(402, 35, 60, 60))
        self.roundbrown_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.roundbrown_2.setText("")
        self.roundbrown_2.setPixmap(QtGui.QPixmap("pics/HMI/icon/Storage golden side.svg"))
        self.roundbrown_2.setScaledContents(True)
        self.roundbrown_2.setObjectName("roundbrown_2")
        self.roundblack_7 = QtWidgets.QLabel(self.ltemodule)
        self.roundblack_7.setGeometry(QtCore.QRect(402, 35, 60, 60))
        self.roundblack_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.roundblack_7.setText("")
        self.roundblack_7.setPixmap(QtGui.QPixmap("pics/HMI/icon/Storage brown side.svg"))
        self.roundblack_7.setScaledContents(True)
        self.roundblack_7.setObjectName("roundblack_7")
        self.transfereddata = QtWidgets.QLabel(self.ltemodule)
        self.transfereddata.setGeometry(QtCore.QRect(405, 60, 50, 10))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.transfereddata.setFont(font)
        self.transfereddata.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(152, 124, 88);")
        self.transfereddata.setAlignment(QtCore.Qt.AlignCenter)
        self.transfereddata.setObjectName("transfereddata")
        self.roundblack_8 = QtWidgets.QLabel(self.ltemodule)
        self.roundblack_8.setGeometry(QtCore.QRect(284, 60, 65, 16))
        self.roundblack_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.roundblack_8.setText("")
        self.roundblack_8.setPixmap(QtGui.QPixmap("pics/HMI/icon/Speed graph line.svg"))
        self.roundblack_8.setScaledContents(True)
        self.roundblack_8.setObjectName("roundblack_8")
        self.straightbar_4 = QtWidgets.QLabel(self.ltemodule)
        self.straightbar_4.setGeometry(QtCore.QRect(374, 40, 2, 50))
        self.straightbar_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.straightbar_4.setText("")
        self.straightbar_4.setPixmap(QtGui.QPixmap("pics/HMI/icon/gps road line.svg"))
        self.straightbar_4.setScaledContents(True)
        self.straightbar_4.setAlignment(QtCore.Qt.AlignCenter)
        self.straightbar_4.setObjectName("straightbar_4")
        self.high_8 = QtWidgets.QLabel(self.ltemodule)
        self.high_8.setGeometry(QtCore.QRect(285, 100, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.high_8.setFont(font)
        self.high_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.high_8.setLineWidth(0)
        self.high_8.setAlignment(QtCore.Qt.AlignCenter)
        self.high_8.setObjectName("high_8")
        self.transferspeed = QtWidgets.QLabel(self.ltemodule)
        self.transferspeed.setGeometry(QtCore.QRect(280, 45, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.transferspeed.setFont(font)
        self.transferspeed.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(152, 124, 88);")
        self.transferspeed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.transferspeed.setObjectName("transferspeed")
        self.high_9 = QtWidgets.QLabel(self.ltemodule)
        self.high_9.setGeometry(QtCore.QRect(400, 100, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.high_9.setFont(font)
        self.high_9.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;\n"
"color: rgb(255, 255, 255);")
        self.high_9.setLineWidth(0)
        self.high_9.setAlignment(QtCore.Qt.AlignCenter)
        self.high_9.setObjectName("high_9")
        self.locationlabel_10.raise_()
        self.roundblack_5.raise_()
        self.storagedatalabel_2.raise_()
        self.lteSignal.raise_()
        self.straightbar_2.raise_()
        self.roundblack_6.raise_()
        self.awsConnectivity.raise_()
        self.straightbar_3.raise_()
        self.roundblack_7.raise_()
        self.transfereddata.raise_()
        self.roundblack_8.raise_()
        self.straightbar_4.raise_()
        self.roundbrown_2.raise_()
        self.high_8.raise_()
        self.transferspeed.raise_()
        self.high_9.raise_()
        figma.setCentralWidget(self.centralwidget)

        self.retranslateUi(figma)
        QtCore.QMetaObject.connectSlotsByName(figma)

    def retranslateUi(self, figma):
        _translate = QtCore.QCoreApplication.translate
        figma.setWindowTitle(_translate("figma", "MainWindow"))
        self.timelabel.setText(_translate("figma", ""))
        self.recordlabel.setText(_translate("figma", "Record"))
        self.timer.setText(_translate("figma", "0:00:00"))
        self.storagelabel.setText(_translate("figma", "Storage space"))
        self.remain.setText(_translate("figma", "  Remain"))
        self.storagedatalabel.setText(_translate("figma", ""))
        self.locationlabel_2.setText(_translate("figma", "ADS-B SDR"))
        self.adsstatus.setText(_translate("figma", ""))
        self.locationlabel.setText(_translate("figma", ""))
        self.latfix.setText(_translate("figma", "LAT"))
        self.distancelabel.setText(_translate("figma", ""))
        self.timelabel_2.setText(_translate("figma", ""))
        self.longfix.setText(_translate("figma", "LONG"))
        self.interiorcma.setText(_translate("figma", "Interior Camera"))
        self.incamstatus.setText(_translate("figma", ""))
        self.excamera.setText(_translate("figma", "Exterior Camera"))
        self.incamstatus_4.setText(_translate("figma", ""))
        self.radio.setText(_translate("figma", "Radio Signal"))
        self.med.setText(_translate("figma", "Med"))
        self.low.setText(_translate("figma", "Low"))
        self.high.setText(_translate("figma", "High"))
        self.cabinmic_2.setText(_translate("figma", "Cabin Mic"))
        self.micstatus.setText(_translate("figma", ""))
        self.wificard_2.setText(_translate("figma", "Wifi Card"))
        self.wificardstatus.setText(_translate("figma", ""))
        self.conecteddevice.setText(_translate("figma", "Connected Devices"))
        self.high_2.setText(_translate("figma", ""))
        self.high_3.setText(_translate("figma", ""))
        self.high_4.setText(_translate("figma", ""))
        self.high_5.setText(_translate("figma", ""))
        self.high_6.setText(_translate("figma", ""))
        self.high_7.setText(_translate("figma", ""))
        self.locationlabel_10.setText(_translate("figma", "LTE Module"))
        self.storagedatalabel_2.setText(_translate("figma", "LTE"))
        self.lteSignal.setText(_translate("figma", ""))
        self.awsConnectivity.setText(_translate("figma", ""))
        self.transfereddata.setText(_translate("figma", ""))
        self.high_8.setText(_translate("figma", "Speed"))
        self.transferspeed.setText(_translate("figma", ""))
        self.high_9.setText(_translate("figma", "transfered"))

